@startuml
'https://plantuml.com/class-diagram

class Main extends Application
class FXMLController implements Initializable
interface Initializable
class Application
class Task


FXMLController <|- Validation
FXMLController <|- Task
FXMLController <|- Actions

class Main
{
+start(Stage window) throws IOException
+main(String []args)
}

class FXMLController
{
+public MenuItem saveList;
+public MenuItem loadList;

+public Button newTask;
+public TextField descriptionField;
+public TextField dueDateField;
+public MenuItem remTask;
+public RadioButton allButton;
+public RadioButton incButton;
+public RadioButton compButton;

+public ObservableList<Task> toDos;
+public ObservableList<Task> compItems;
+public ObservableList<Task> incItems;
+public TableView<Task> tableView;
+public TableColumn<Task,String> descriptCol;
+public TableColumn<Task,String> dueDateCol;
+public TableColumn<Task,String> CheckCol;

+public void initialize(URL url, ResourceBundle rb)
+public void changeDescript(TableColumn.CellEditEvent editedCell)
+public void changeDate(TableColumn.CellEditEvent editedCell)
+public void changeComp(TableColumn.CellEditEvent editedCell)
+public void addTaskButton(ActionEvent event)
+public void removeTaskButton(ActionEvent event)
+public void displayAll(ActionEvent event)
+public void displayComp(ActionEvent event)
+public void displayIncomp(ActionEvent event)

+public void saveListButton(ActionEvent event)
+public void loadListButton(ActionEvent event)

}

class Task
{
+private static CheckBox select;
+private final SimpleStringProperty description;
+private boolean complete;
+private final SimpleStringProperty dueDate;

+public boolean isComplete()
+public void setCompleted(boolean completed)

+public String getDescription()
+public SimpleStringProperty descriptionProperty()
+public void setDescription(String description)
+public String getDescription()

+public SimpleStringProperty getDueDate()
+public void setDueDate(String dueDate)
+public void getDueDate(String dueDate)

}

class Validation
{
+public static void getChecked(TableView<Task> list, ObservableList<Task> compItems, ObservableList<Task> incItems);
+public static boolean isDateValid(String date);
+public static boolean isDescrValid(String df);


}

class Actions
{
+public static void removeTask(Task select,ObservableList<Task> compItems, ObservableList<Task> incItems, ObservableList<Task> toDos) {
+public static void addTask( ObservableList<Task> list, Task errand) {
+public static void toCSV(ObservableList<Task> all, File file) throws IOException {
+public static void fromCSV( File file, ObservableList<Task> comp, ObservableList<Task> inc, ObservableList<Task> all) throws IOException {
+public static void save(FileChooser saver, ObservableList<Task> all) {
+public static void open(FileChooser saver, ObservableList<Task> comp, ObservableList<Task> inc, ObservableList<Task> all) {


}

@enduml